### ISSUE TITLE
OutOfMemoryException Encrypting Large File 

### ISSUE THREAD

**Issue by aarondglover** [stanac/EasyCrypto#1]
I was attempting to encrypt a binary file of 360MB, and the following exception is raised.

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Security.Cryptography.CryptoStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at EasyCrypto.AesEncryption.Encrypt(CryptoRequest request)
   at EasyCrypto.AesEncryption.EncryptAndEmbedIv(Stream dataToEncrypt, Byte[] key, Stream destination, Byte[] salt)
   at EasyCrypto.AesEncryption.EncryptWithPassword(Stream dataToEncrypt, String password, Stream destination)
   at EasyCrypto.AesEncryption.<>c__DisplayClass3_0.<EncryptWithPassword>b__0(Stream inStream, Stream outStream)
   at EasyCrypto.AesEncryption.HandleByteToStream(Byte[] data, Action`2 action)
   at EasyCrypto.AesEncryption.EncryptWithPassword(Byte[] dataToEncrypt, String password)

```

**Comment by stanac** [comment]
Please look at the https://stanac.github.io/EasyCrypto/EasyCrypto/AesFileEncrytion.htm and updated readme, it contains method descriptions for file encryption/decryption. At my local dev machine it took about 60-90 seconds to encrypt or decrypt file of that size. You would need nuget 3.2.1 for those methods to be available.

Please let me know if this solution is something you are ok with. Thanks

**Comment by aarondglover** [comment]
Hi stanac,

The new  AesFileEncrytion methods do work, but on large files, it is really quite slow. I will gather some numbers together to share with you. 

Is there any chance you could consider adding some overloads to the AesFileEncrytion methods to accept a cancellation token in order to support cancellation. I can open a new issue/feature request.

I just had a cursory glance at the code, I understand this change would touch a lot of methods, because ultimately you need to push the cancellation token all the way down to the method;

`internal static async Task EncryptAsync(CryptoRequest request)`

but I think it is a worth while pursuit. 

Fantastic work on the library thus far.

**Comment by aarondglover** [comment]
It seems I was most unfair with my last assertion that it is slow. Without the Visual Studio debugger attached, the performance is most reasonable.

**360MB Binary File Encrypted in 1m01secs**

Happy Days
